version: "3.8"
services:
    jfl:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            network: host
        ports:
            - "8001:80"
        # should Nginx crash, always restart it
        restart: always
        volumes:
            # Nginx should pick up local changes to files in ./public
            - ./public:/var/www/html