version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3080:3080"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./certs:/etc/app/certs # Local certificate for jsonformatter.localhost
    depends_on:
      - nextjs

volumes:
  caddy_data:
  caddy_config:
