[build]
command = "npm run build"
publish = "dist/"

[build.environment]
NODE_VERSION = "22.6.0"
NPM_VERSION = "10.9"

[[headers]]
for = '~* ".(ico|css|js|gif|jpe?g|png)$"'
[headers.values]
expires = '7d'
cache-control = 'public'

[[headers]]
for = "/service-worker.js"
[headers.values]
cache-control = '''
	no-cache,
	no-store,
	must-revalidate'''

[[headers]]
for = "/manifest.json"
[headers.values]
cache-control = '''
	no-cache,
	no-store,
	must-revalidate'''

##############
# REDIRECTS
##############

[[redirects]]
from = "http://www.jsonformatter.com/"
to = "https://jsonformatter.com/"
status = 301
force = true

#.live -> .com
[[redirects]]
from = "http://www.jsonformatter.live/"
to = "https://jsonformatter.com/"
status = 301
force = true

[[redirects]]
from = "https://www.jsonformatter.live/"
to = "https://jsonformatter.com/"
status = 301
force = true

[[redirects]]
from = "http://jsonformatter.live/"
to = "https://jsonformatter.com/"
status = 301
force = true

[[redirects]]
from = "https://jsonformatter.live/"
to = "https://jsonformatter.com/"
status = 301
force = true
