name: End-to-end tests

on: [push]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: make test
