name: End-to-end tests

on: [push]

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: make run-prod

      - name: Run tests
        run: make test
