name: tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "23.6"

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test
